### PR TITLE
ral_dev flake8 fixes [NOT READY TO MERGE]

### PR DESCRIPTION
**Pull request by crteja**
- Fixed all of the flake8 lint errors in `pyuvm` source files
- Found a false positive issue
  - `error_out` uses an assert statement as follows  
     - ` assert (<condition>, <message>)`  
     - because of the paranthesis, the whole block inside it is considered as a single expression and assert was always evaluated as `True`. 
     - So, even though there are some test failures they are not reported.
     - This was observed while fixing flake8 lint errors 
     - I've fixed most of them, there are three failures still 

@EngRaff92, Would you be able to look in to the remaining ? I think they will show up in the CI

### CODE REVIEW

**Comment by EngRaff92** [comment]
> * Fixed all of the flake8 lint errors in `pyuvm` source files
> * Found a false positive issue
>   
>   * `error_out` uses an assert statement as follows
>     
>     * ` assert (<condition>, <message>)`
>     * because of the paranthesis, the whole block inside it is considered as a single expression and assert was always evaluated as `True`.
>     * So, even though there are some test failures they are not reported.
>     * This was observed while fixing flake8 lint errors
>     * I've fixed most of them, there are three failures still
> 
> @EngRaff92, Would you be able to look in to the remaining ? I think they will show up in the CI

Thanks so much but that is exactly what I meant initially I’ve already fixed all the flake8 error assuming we do both deliver we have a clash to be reviewed. Let me know

**Comment by crteja** [comment]
@EngRaff92 , its ok. 
Would you be able to raise a PR with your changes. I will rebase this PR on `ral_dev` once your changes are merged. 

also, Could update the discussion board with the issue you are working on so that I can look in to other open items.

**Comment by raysalemi** [comment]
I am glad you caught the `assert` error.

**Comment by EngRaff92** [comment]
> @EngRaff92 , its ok. Would you be able to raise a PR with your changes. I will rebase this PR on `ral_dev` once your changes are merged.
> 
> also, Could update the discussion board with the issue you are working on so that I can look in to other open items.

yes once I finally manage the merge I will update the table at the beginning

**Comment by crteja** [comment]
> just to recap steps to sync my `EngRaff92:register_model_dev` branch into `pyuvm:ral_dev`:
> 
> 1. git checkout `register_model_dev` -- yes already here -- DONE
> 2. git add and git commit to put all your changes on the PR branch -- DONE
> 3. git fetch --all to get the ral_dev branch -- DONE
> 4. git rebase ral_dev to rebase your PR branch to ral_dev -- DONE my register_model_dev is updated
> 5. git checkout ral_dev to check out ral_dev -- DONE moved onto the new one
> 6. git merge  to get your commits into ral_dev -- Does not work it says it cannot work merging from EngRaff92:register_model_dev
> 7. git push to push your commits to the repository. -- NOT HERE yet
> 
> am I missing something ? because what I'm doing is to merge 2 repos branches not 2 branches from the same repo.

Have you tried this command to merge ? 
`git merge origin/register_model_dev` while on `ral_dev` branch.
Since you are working on a fork pyuvm, your fork is the origin of the local repo.

**Comment by EngRaff92** [comment]
it does say already updated but I do believe frankly it did not work at all

**Comment by crteja** [comment]
> it does say already updated but I do believe frankly it did not work at all

ok. I'm not sure about this issue. Were you able to push local updates in `register_model_dev` to your pyuvm fork ? 
if so, please do, we can raise a PR to `ral_dev` using github UI

**Comment by EngRaff92** [comment]
> > it does say already updated but I do believe frankly it did not work at all
> 
> ok. I'm not sure about this issue. Were you able to push local updates in `register_model_dev` to your pyuvm fork ? if so, please do, we can raise a PR to `ral_dev` using github UI

yes that PR is updated but I still cannot see any commit from me into the ral_dev. I try to push my changes into the ral_dev but it keeps saying is updated. Weird

**Comment by raysalemi** [comment]
There are conflicts on #165

**Comment by raysalemi** [comment]
This PR seems to be pushing to a branch other than `ral_dev` or `master`.  It says `crteja/pyuvm`

**Pull request closed without merging**
