### PR TITLE
Ral dev

### PR DESCRIPTION
**Pull request by EngRaff92**

### CODE REVIEW

**Comment by EngRaff92** [comment]
the following are the changes:

- full implementation of `uvm_reg_map`
- full implementation of `uvm_reg_block`
- only `BACKDOOR` support still ongoing
- fixing flake8 errors (line length as well)
- replaced `_pyuvm_` with `_uvm_` keeping everything consistent with project
- adding `_` to internal variables (no `_` for internal methods)
- adding type checking in internal class functions
- adding `submaps` support
- adding more tests on `uvm_reg_map`
- added TODOs to almost every class (few still pending)
- started `uvm_reg write test`

all the files have been fixed

**Comment by raysalemi** [comment]
I am not sure why we are not running the tox checks.  They fail, but I have fixed the conflicts.

**Comment by EngRaff92** [comment]
> I am not sure why we are not running the tox checks. They fail, but I have fixed the conflicts.

I do run tox command before every commit. I believe the command works only and only on Linux and doesn’t support macOS

**Comment by raysalemi** [comment]
This seems to still have conflicts.  Also it fails flake8

**Comment by raysalemi** [comment]
Here are the conflicts I see in one of the test files:

```

<<<<<<< HEAD:tests/pytests/test_uvm_reg_block.py
    reg = uvm_reg()
    reg.configure(block,"0x4","")
    assert block.get_registers() == [reg]
=======
    reg = temp_reg()
    reg.configure(block, "0x4", "")
    block.set_lock()
    assert block._get_registers() == [reg]

>>>>>>> c215fd44708cc9708bc6e594b2dc96dacc5c5bc6:tests/pytests/test_pyuvm_reg_block.py

```

**Comment by EngRaff92** [comment]
> Here are the conflicts I see in one of the test files:
> 
> ```
> 
> <<<<<<< HEAD:tests/pytests/test_uvm_reg_block.py
>     reg = uvm_reg()
>     reg.configure(block,"0x4","")
>     assert block.get_registers() == [reg]
> =======
>     reg = temp_reg()
>     reg.configure(block, "0x4", "")
>     block.set_lock()
>     assert block._get_registers() == [reg]
> 
> >>>>>>> c215fd44708cc9708bc6e594b2dc96dacc5c5bc6:tests/pytests/test_pyuvm_reg_block.py
> ```

the differences are only due checks I put in place in the uvm reg. After merging the tests the make test command should pass

**Comment by EngRaff92** [comment]
> This seems to still have conflicts. Also it fails flake8

Still failing flake8, mmmm weird my vscode is absolutely clean. What is the reference in the log that tells you about flake8 I will check at my end as well. Probably flake8 in vscode is more forgiving then the one in tox

**Comment by raysalemi** [comment]
I am deleting branch `pr_169` from the repository.  I put it up there by accident and it is causing issues.

**Comment by raysalemi** [comment]
I have merged this, though we may still need to fix flake8 and tests.

**Comment by raysalemi** [comment]
> > This seems to still have conflicts. Also it fails flake8
> 
> Still failing flake8? mmmm weird my vscode is absolutely clean. What is the reference in the log that tells you about flake8 ? I will check at my end as well. Probably flake8 in vscode is more forgiving then the one in tox

Are you running on `ral_dev` from the repository?  I think there are differences between `ral_dev` in GitHub and your branch.

**Comment by raysalemi** [comment]
> > This seems to still have conflicts. Also it fails flake8
> 
> Still failing flake8? mmmm weird my vscode is absolutely clean. What is the reference in the log that tells you about flake8 ? I will check at my end as well. Probably flake8 in vscode is more forgiving then the one in tox

Here is the git log I am seeing:

```
154227c Tue Aug 15 16:52:50 2023 -0400 Ray Salemi (HEAD -> ral_dev, origin/ral_dev) Merge branch 'EngRaff92-ral_dev' into ral_dev
b8412c3 Tue Aug 15 16:52:30 2023 -0400 Ray Salemi (EngRaff92-ral_dev) fixed conflicts
c215fd4 Tue Aug 15 20:47:23 2023 +0100 EngRaff92 Merge pull request #2 from EngRaff92/register_model_dev
93cf17e Tue Aug 15 20:17:32 2023 +0100 EngRaff92 fix make test
ebd9611 Tue Aug 15 15:16:55 2023 -0400 Ray Salemi add ral_dev to workflow
```

Do you have these commits?

**Comment by EngRaff92** [comment]
I fixed everything finally here `pyuvm:ral_dev` I just have to push. Unfortunately this is quite annoying because git push is giving me this error: `remote: Permission to pyuvm/pyuvm.git denied to EngRaff92`. 

I'm googling for a solution. Anyway in my cloned `pyuvm:ral_dev` everything is fixed. Definitely anyway viscide flake8 is more forgiving then the used flake8

**Comment by raysalemi** [comment]
You can make a new PR

**Comment by EngRaff92** [comment]
> You can make a new PR

sure but that would go from `EngRaff92:ral_dev` to `pyuvm:ral_dev` is that ok for you? I do believe I do not have write access to `pyuvm:ral_dev`.

**Comment by raysalemi** [comment]
Yes

**Pull request merged**
