### PR TITLE
Add Github Actions integration

### PR DESCRIPTION
**Pull request by themperek**
Add some basic Github Actions CI check.
Also flake8 that fails at the moment.

Example: https://github.com/themperek/pyuvm/actions/runs/862989949

### CODE REVIEW

**Comment by raysalemi** [comment]
Thanks! I did not know how to do this.

**Comment by themperek** [comment]
BTW

Some errors from flake8: https://github.com/pyuvm/pyuvm/runs/2639470999?check_suite_focus=true (under `flak8`)

**Comment by raysalemi** [comment]
flake8 is a linter?

**Comment by themperek** [comment]
>flake8 is a linter?
As iI understand It is a Python library that wraps different linters. In practice yes.

PS. You may also check  https://github.com/psf/black (`black --line-length 120` to have longer lines)

**Pull request merged**
