### PR TITLE
Add default argument to ConfigDB().get()

### PR DESCRIPTION
**Pull request by timothyscherer**
Implements changes discussed in #177.

### CODE REVIEW

**Comment by raysalemi** [comment]
Why is default_get set to object() rather than None at the start?

**Comment by timothyscherer** [comment]
Because someone may want to intentionally use `None` as their default return value, which is a global constant to the same exact object. In order to catch the object, the default needs to be a completely unique object (`is` uses `id(obj)` which is unique to that object aka a pointer) that the user will never pass as a default value.

By using `object()`, it is guaranteed that the exception will only get raised if no value for `default` was given.

**Comment by raysalemi** [comment]
That makes sense. 

Does using the `is` remove the need to use the id?

**Comment by timothyscherer** [comment]
The "under-the-hood" implementation of `is` compares `id()` of both objects, so it checks to see if they are the same object. These changes only use `is`.

`if default is self.default_get` is  functionally equivalent to `if id(default) == id(self.default_get)`.

**Comment by raysalemi** [comment]
Yes. The `is` is just cleaner and more Pythonic.

**Comment by raysalemi** [comment]
Thanks for the improvement!

**Pull request merged**
