### PR TITLE
Cocotb record.name deletion in LOG

### PR DESCRIPTION
**Pull request by svenka3**
As per ongoing discussion https://github.com/pyuvm/pyuvm/discussions/126

I am submitting the agreed fix for removing that redundant redcord.name/full_name. 

Also included is a minor fix for issue: https://github.com/pyuvm/pyuvm/issues/128

### CODE REVIEW

**Comment by raysalemi** [comment]
Thanks!

Please update this PR so that it passes the `flake8` linting check.

**Comment by svenka3** [comment]
Sorry for the noise in this Lint fix cycle. To begin with I am unable to run flake8 on my local CentOS7 (strange, will open a different ticket). So it took few iterations here to clean up. Secondly most of this code comes from cocotb log.py which I believe is not flake8 clean - most of the errors came from that (or from my local gvim setting on tab-vs-space, I fixed those). 

Now I see we have 2 rules enabled: 
https://www.flake8rules.com/rules/W504.html
https://www.flake8rules.com/rules/W503.html

This I believe is a conflict and we need to choose one. @raysalemi can you please comment?

Thanks

**Comment by raysalemi** [comment]
I'm wondering, why do we have cocotb's log.py in the release tree?

**Comment by svenka3** [comment]
I borrowed some code from log.py to clean up this logging scheme and that piece of code has lint issues

**Comment by raysalemi** [comment]
Ah…

**Comment by raysalemi** [comment]
I'd say go with the most recent listing rule.

**Comment by svenka3** [comment]
So we waive off W503? Please guide me on how to add that waiver in pyuvm workflow for flake8.

Thanks

**Comment by raysalemi** [comment]
I think the waivers are in tox.ini

**Comment by svenka3** [comment]
At last, "All checks have passed"..sometimes the smallest task becomes the critical path, once again sorry for too many iterations. Good thing is I learnt basic flake8 on the way, thanks @raysalemi :-)

**Comment by miserva** [comment]
I tried this change out and while I like removing the redundancy from the messages, I could see a few issues with this approach. The first was that messages coming from cocotb were misaligned with messages from pyuvm.
```
# 501000.00ns INFO     cocotb.regression                  running FibonacciTest (3/4)
#                                                           Run Fibonacci program
# 670000.00ns INFO        testbench.py(134)[]: Fibonacci Sequence: [0, 1, 1, 2, 3, 5, 8, 13, 21]
# 671000.00ns INFO     cocotb.regression                  FibonacciTest passed
# 671000.00ns INFO     cocotb.regression                  running AluTestErrors (4/4)
#                                                           Test ALU with errors on all operations
# 920000.00ns ERROR       testbench.py(218)[uvm_test_top.env.scoreboard]: FAILED: 0xc8 ADD 0x3a = 0x0102 expected 0x0103
```
The second is that copying the source code from cocotb's log module means it will not receive the future updates to the module. Also I'm not sure if there are some copyright issues in copying that much code.

If I may suggest an alternative approach, the redundancy could be removed only with a minor tweak to `PyuvmFormatter`, turning the `record.name` space into something useful.
```python
class PyuvmFormatter(SimColourLogFormatter):
    def __init__(self, full_name):
        self.full_name = full_name
        super().__init__()

    def format(self, record):
        new_msg = f"[{self.full_name}]: " + record.msg
        record.msg = new_msg
        name_temp = record.name
        record.name = f"{record.pathname}({record.lineno})"
        formatted_record = super().format(record)
        record.name = name_temp
        return formatted_record
```
Example output:
```
# 501000.00ns INFO     cocotb.regression                  running FibonacciTest (3/4)
#                                                           Run Fibonacci program
# 670000.00ns INFO     ..amples/TinyALU/testbench.py(134) []: Fibonacci Sequence: [0, 1, 1, 2, 3, 5, 8, 13, 21]
# 671000.00ns INFO     cocotb.regression                  FibonacciTest passed
# 671000.00ns INFO     cocotb.regression                  running AluTestErrors (4/4)
#                                                           Test ALU with errors on all operations
# 920000.00ns ERROR    ..amples/TinyALU/testbench.py(218) [uvm_test_top.env.scoreboard]: FAILED: 0x29 ADD 0xa0 = 0x00c9 expected 0x00ca
```
The messages would look a lot like in SystemVerilog UVM.

**Comment by svenka3** [comment]
I like the alternate implementation to fix the issue. Kudos to @miserva

**Comment by raysalemi** [comment]
I agree with the suggestion. I hadn't realized the copied code was relying on synchronization with **cocotb**.  I thought it was just being used as a code example.  This PR is failing due to conflicts.  I'll try to reset the HEAD back to before the last PR.

**Comment by raysalemi** [comment]
Please create a new pull request with the new code.

**Comment by raysalemi** [comment]
I have rolled HEAD back to the previous commit.  Now a new pull request can
implement the new approach.

**Pull request closed without merging**
