### PR TITLE
Migrate unit tests to pytest

### PR DESCRIPTION
**Pull request by tudortimi**

### CODE REVIEW

**Comment by tudortimi** [comment]
I migrated the two modules in `pytests` to fully use `pytest`. I did the changes across many small commits to that it's easier to see what's going on.

**Comment by tudortimi** [comment]
I noticed that some tests in `cocotb_tests` are actually just regular `unitest` tests. They don't seem to be running in the CI at the moment. I left them alone for now, as moving them should be done in a separate PR.

**Comment by raysalemi** [comment]
This is amazing!  I can see why you recommended switching.

**Comment by raysalemi** [comment]
Accepting all of these changes. A *much* cleaner test structure!

**Pull request merged**
