### PR TITLE
Change "UVMNotImplemented" error to "UsePythonMethod" error  when applicable

### PR DESCRIPTION
**Pull request by hzisman**

### CODE REVIEW

**Comment by raysalemi** [comment]
Did I create the `UsePythonMethod` exception and then not use it?

**Comment by raysalemi** [comment]
The test failed. I wonder if it expects the previous exception.

**Comment by hzisman** [comment]
> Did I create the UsePythonMethod exception and then not use it?

You use, but there are still cases you use "UVMNotImplemented" when It should be "UsePythonMethod"

**Comment by hzisman** [comment]
> The test failed. I wonder if it expects the previous exception.

Yes, it does 
for example: https://github.com/pyuvm/pyuvm/blob/eecfb4be7ee08350d02c8a1ca90b9e74f4e4c32f/tests/pytests/test_05_base_classes.py#L107-L108
I'll send changes for the tests as well

**Comment by raysalemi** [comment]
Thank you!

**Pull request merged**
